-- MySQL Script generated by MySQL Workbench
-- Thu Apr 20 14:16:16 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema restaurante_pueba
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema restaurante_pueba
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `restaurante_pueba` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `restaurante_pueba` ;

-- -----------------------------------------------------
-- Table `restaurante_pueba`.`reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante_pueba`.`reserva` (
  `idReserva` INT NOT NULL AUTO_INCREMENT,
  `idCliente` INT NOT NULL,
  `Fecha` DATE NOT NULL,
  `Hora` TIME NOT NULL,
  `Numero_de_personas` INT NOT NULL,
  `idMesa` INT NOT NULL,
  `Observaciones` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`idReserva`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'reservas por los clientes del restaurante';


-- -----------------------------------------------------
-- Table `restaurante_pueba`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante_pueba`.`clientes` (
  `idClientes` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `Direccion` VARCHAR(45) NOT NULL,
  `Telefono` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idClientes`),
  CONSTRAINT `fk_clientes_reserva`
    FOREIGN KEY (`idClientes`)
    REFERENCES `restaurante_pueba`.`reserva` (`idReserva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'informacion de los clientes del restaurante ';


-- -----------------------------------------------------
-- Table `restaurante_pueba`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante_pueba`.`pedidos` (
  `idPedido` INT NOT NULL AUTO_INCREMENT,
  `idMesa` INT NOT NULL,
  `idEmpleados` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `total` DECIMAL(10,0) NOT NULL,
  PRIMARY KEY (`idPedido`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'se gestionan los pedidos del cliente';


-- -----------------------------------------------------
-- Table `restaurante_pueba`.`detalle pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante_pueba`.`detalle pedido` (
  `idDetalle` INT NOT NULL AUTO_INCREMENT,
  `idPedido` INT NOT NULL,
  `idPlato` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `subtotal` DECIMAL(10,0) NOT NULL,
  PRIMARY KEY (`idDetalle`),
  CONSTRAINT `fk_detalle pedido_pedidos1`
    FOREIGN KEY (`idDetalle`)
    REFERENCES `restaurante_pueba`.`pedidos` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `restaurante_pueba`.`empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante_pueba`.`empleados` (
  `idEmpleados` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellidos` VARCHAR(45) NOT NULL,
  `Cargo` VARCHAR(45) NOT NULL,
  `Salario` FLOAT NOT NULL,
  PRIMARY KEY (`idEmpleados`),
  CONSTRAINT `fk_empleados_pedidos1`
    FOREIGN KEY (`idEmpleados`)
    REFERENCES `restaurante_pueba`.`pedidos` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'informacion de los empleados';


-- -----------------------------------------------------
-- Table `restaurante_pueba`.`menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante_pueba`.`menu` (
  `idPlato` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Descripcion` VARCHAR(100) NOT NULL,
  `Precio` FLOAT NOT NULL,
  `Categoria` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idPlato`),
  CONSTRAINT `fk_menu_detalle pedido1`
    FOREIGN KEY (`idPlato`)
    REFERENCES `restaurante_pueba`.`detalle pedido` (`idDetalle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'el menu del restaurante con diferentes platos ';


-- -----------------------------------------------------
-- Table `restaurante_pueba`.`mesas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurante_pueba`.`mesas` (
  `idmesas` INT NOT NULL AUTO_INCREMENT,
  `Numero_de_mesa` INT NOT NULL,
  `Capacidad` INT NOT NULL,
  `Estado` VARCHAR(45) NOT NULL,
  `Ubicacion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idmesas`),
  CONSTRAINT `fk_mesas_pedidos1`
    FOREIGN KEY (`idmesas`)
    REFERENCES `restaurante_pueba`.`pedidos` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
